### ISSUE TITLE
Issue: no descriptions on GitHub labels leads to inconsistent interpretation

### ISSUE THREAD

**Issue by billglover** [codebuddies/codebuddies#1124]
**What is the current behaviour?**
We currently have 50 issue labels defined in GitHub. 21 of these are not assigned to open issues (i.e. are unused).

**What is the expected behaviour?**
1. All issue labels should have an issue description set. This description should make it clear when the label should be used and how it should be interpreted.
2. It should be clear, and documented, how issue labels are being used.
3. Unused issue labels should be removed to reduce confusion.

**How can this bug be reproduced?**
See the [issues page](https://github.com/codebuddies/codebuddies/labels).

**Comment by billglover** [comment]
The beauty of labels is that they are fairly flexible, but I've found myself struggling to know how to use them and occasionally clashing with a different interpretation on how they are used. I've had a quick look through the existing labels and am going to propose the following as a starting point.

Labels for type:
- bug - something isn't working the way you'd expect or you are unable to accomplish a task
- feature - you'd like to enhance an existing feature or propose something new

Labels for state:
- backlog - issue has been raised but hasn't yet been given any consideration, we'll get to it
- in-discussion - this issue is being considered and we'd welcome your thoughts and ideas
- in-progress - this issue is currently being worked on by a member of the community
- in-review - the implementation that addresses this issue is up for review
- closed - this issue is now closed, see comments for more information

Labels for functional area:
- translation - issues that relate to the translation of the site into languages other than English
- hangouts - issues that relate to the hangout functionality
- discussions - issues that relate to the discussions functionality
- messaging - issues that relate to the messaging functionality
- profile - issues that relate to user profiles
- sign-up - issues that relate to sign-up and log-in
- slack - issues that relate to the use of Slack
- forum - issues that relate to the forum
- community - issues that relate to community management

Labels for technology:
- html
- css
- javascript
- infrastructure

Labels for community:
- help-wanted - this is a priority issue and we'd like some extra help
- good-first-issue - this issue is good for a first-time contributor, help and support provided
- claimed - an individual has claimed ownership of this issue

I'm not particularly wedded to any of these labels or the overall categorisation and so I'd welcome thoughts on the above.

**Comment by billglover** [comment]
Comment from Ben D on Slack:

> "For what my two cents is worth: I noticed you have categories for labels. Maybe labels for those categories might be a good intermediary step, which can then lead to more specific labels as the issue progresses?"

I originally used these categories as more of a guide for my thought process, but it is worth thinking about whether they make it into the issue labels themselves. For me, these categories started out as a the list of reasons we use labels. For example: all issues have a type, a state and a functional area. The majority will have a technology and the community labels are would be used as needed.

**Comment by billglover** [comment]
Comment from @angelocordon on Slack:

> "looks great, just did a quick read through and will read deeper when I get back to my desk. I like the direction; I think the other challenge might be we don’t put in enough efforts in trimming our issues list and it gets unwieldily. Perhaps we can think about how this might be more self-served so that people creating issues can apply the right tags themselves?"

This context for this issue was confusion I faced when trying to go through the backlog.

**Comment by lpatmo** [comment]
👏👏This is a lot of work -- thank you so much, Bill. 

A few label additions I've appended to the bottom of some lists:

=================================
Labels for type:

* bug - something isn't working the way you'd expect or you are unable to accomplish a task
* feature - you'd like to enhance an existing feature or propose something new

Labels for state:

* backlog - issue has been raised but hasn't yet been given any consideration, we'll get to it
* in-discussion - this issue is being considered and we'd welcome your thoughts and ideas
* in-progress - this issue is currently being worked on by a member of the community
* in-review - the implementation that addresses this issue is up for review
* closed - this issue is now closed, see comments for more information

Labels for functional area:

* translation - issues that relate to the translation of the site into languages other than English
* hangouts - issues that relate to the hangout functionality
* discussions - issues that relate to the discussions functionality
* inbox - issues that relate to the inbox functionality
* profile - issues that relate to user profiles
* sign-up - issues that relate to sign-up and log-in
* slack - issues that relate to the use of Slack
* forum - issues that relate to the forum
* community - issues that relate to community management
* groups - issues that relate to the /study-groups functionality
* home-page - issues that relate to the landing page

Labels for technology:

* html - issues where the bulk of the work is likely to involve HTML
* css - issues where the bulk of the work is likely to involve CSS
* javascript - issues where the bulk of the work is likely to involve JavaScript
* meteorjs - issues where the solution involves having a basic understanding of MeteorJS
* infrastructure - issues where the bulk of the work is likely to involve infrastructure
* documentation - issues where the bulk of the work involves updating content

Labels for community:

* help-wanted - this is a priority issue and we'd like some extra help
* good-first-issue - this issue is good for a first-time contributor, help and support provided
* claimed - an individual has claimed ownership of this issue

===========
We can adjust/maybe we can keep this thread open for future discussions, but in the meantime, we can start removing unnecessary labels/adding the new ones.

**Comment by billglover** [comment]
I'll take this. I'm going to start by documenting the use of labels so we can have something to reference or point people to. Once I've done that I'll update issue label descriptions on GitHub before looking at the challenge of labelling open issues.

**Comment by lpatmo** [comment]
A suggestion (feel free to argue down): Instead of `slack` or `forum`, etc., use prefixes for those functionalities --
```
* feat-translation - issues that relate to the translation of the site into languages other than English
* feat-hangouts - issues that relate to the hangout functionality
* feat-discussions - issues that relate to the discussions functionality
* feat-inbox - issues that relate to the inbox functionality
* feat-profile - issues that relate to user profiles
* feat-sign-up - issues that relate to sign-up and log-in
* feat-slack - issues that relate to the use of Slack
* feat-forum - issues that relate to the forum
* feat-community - issues that relate to community management
* feat-groups - issues that relate to the /study-groups functionality
* feat-home-page - issues that relate to the landing page
```

I went through and started doing a bit of cleanup/adding descriptions to labels (I didn't know Github allowed it; this is _great_) on https://github.com/codebuddies/codebuddies/labels?page=1&sort=name-asc but haven't finished, so if anyone who's already been added as a collaborator to the repo could finish up, feel free. Thank you!! EDIT: Nvm just saw your comment, Bill. :) Thanks for taking.

**Comment by RuubixO** [comment]
From an outsider, it feels like having both a "category-member" format would be more effective overall, instead of piecemeal.

**Comment by billglover** [comment]
I've added this to the documentation: [contribution/labels](https://github.com/codebuddies/documentation/blob/master/contribution/labels.md).

It doesn't yet seem to be live on the docs site, but I'm assuming this will sync at some point.

I'll make a start on updating GitHub issue definitions today.

**Comment by billglover** [comment]
Now that I'm almost through with implementing this I've started to wonder about the use of the word *feature* to describe functional area. We now have:

* `[type] feature`
* `[feature] hangouts`

Is this confusing, or am I overthinking it? Only alternative I can think of is:

* `[type] feature`
* `[area] hangouts`

Thoughts?

**Comment by billglover** [comment]
Issue labels are now fully documented: https://docs.codebuddies.org/code-contribution/issue/labels
