### ISSUE TITLE
Share Buttons for hangout.

### ISSUE THREAD

**Issue by distalx** [codebuddies/codebuddies#119]
The Share button will give user the ability to engage with people who are not on CB. as well as user could add a personalized message to links before they share on multiple social networks and platforms.

**Comment by lpatmo** [comment]
Two options to discuss, before we mark this issue for `Hacktoberfest`: 

- We can use a meteor social share package? (Most of them look pretty old.)
- We can just integrate twitter sharing, and manually write in the twitter share link (http://stackoverflow.com/questions/6208363/sharing-a-url-with-a-query-string-on-twitter)

**Comment by distalx** [comment]
I'd suggest carrot/share-button https://github.com/carrot/share-button

**Comment by lpatmo** [comment]
> should we also consider automatically posting to social media platforms from CB once a new hangout is created? Using the CB social media accounts? 

@sergeant-q @distalx submitted PR #333 that accomplishes this. :) That is, when a hangout is created on codebuddies.org, a tweet about it is automatically posted to http://twitter.com/codebuddiesmeet.

We're not really on other social media platforms apart from the Facebook group we technically share with The Odin Project because the name of that group is called https://www.facebook.com/groups/TOPSTUDYGROUP/, and TOP links to it as one of their study groups at http://www.theodinproject.com/studygroups. (Maybe one day we can create a Facebook page or something, but until then...)

But anyway, yes, individual social media sharing is a separate issue. :)

**Comment by distalx** [comment]
@sergeant-q It appears that They have recently declared it as `Currently Unmaintained`.

@lpatmo I'm thinking about covering `twitter`, `facebook`, `linkedin`, and `gplus`.

**Comment by billglover** [comment]
Closing this issue as stale. If this feature is still of interest, please open a new issue and include a reference to this issue by including issue number #119 in the description.
