### ISSUE TITLE
Figure out import solution for mailing newsletter

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#143]
Mailing newsletter: figure out a way to automatically import Slack signups into tinyletter.com/codebuddies, or use a service besides tinyletter to make it easier to send out community-wide email announcements.

**Comment by wuworkshop** [comment]
According to this link - https://tinyletter.desk.com/customer/en/portal/articles/1470842-importing-subscribers

> You can import subscribers, but keep in mind that we require all subscribers to have opted-in to receive your newsletters before they can be added. (Imported subscribers will not receive notice that they have been added to your list.)

**Comment by lpatmo** [comment]
I used to import the email addresses from Slack manually, but it got to be too much of a hassle, and also I'd need to keep track of which email address I imported last so I didn't accidentally re-import someone who'd unsubscribed. 

We might need to get off tinyletter and use a custom mailer to add users to a list more easily.

**Comment by distalx** [comment]
When user sign in for the first time to coddebuddies.org we can add them to mailing list using apis.

**Comment by lpatmo** [comment]
Mailchimp is a good start -- thanks @distalx. If we grow to roughly 5000 subscribers or more we may want to consider migrating to Sendgrid, which is a lot cheaper but will take more work. Right now we're around 1500 subscribers not including the new members on Slack, but the list needs to be cleaned.

**Comment by wuworkshop** [comment]
Mailgun's pricing looks pretty affordable as well. Your first 10,000 emails are free every month.

Also, maybe the user's profile settings should have a checkbox or something where they can opt-in by checking the box and unsubscribe by unchecking the box to the newsletter. I agree with Tiny Letter's policy, the user should explicitly opt-in to the newsletter. Don't automatically add them just because they've logged in to the CB app.

**Comment by anbuselvan** [comment]
I second @wuworkshop's recommendation as I'm using mailgun for 3 of my clients and there is no problem so far and it's very easy to integrate with meteor as well.

<img width="612" alt="mailgun-invoice" src="https://cloud.githubusercontent.com/assets/167158/16709608/ce17c2a0-45ca-11e6-8933-73a1c7d64ac6.png">

**Comment by lpatmo** [comment]
Sorry for the slow response to this thread.

@anbuselvan Are you using Mailgun mainly for transactional emails, or are you also using it for mailing newsletters? I thought it was primarily used for the former.

@wuworkshop I'm for the unsubscribe link being visible in all mailings, but I think it's the default in a lot of sites for newly registered users to receive at least a welcome email from the site/platform they signed up for. Maybe we can include a checkbox for people to unsubscribe from the newsletter directly in the app, but I don't know if we need to explicitly ask them to check the checkbox to opt into the mailing list from the start. That's just my opinion, though. Open to thoughts.

**Comment by anbuselvan** [comment]
@lpatmo it's been used for both newsletters and other emails like notifications etc., An interesting story that when we first sent out about 8000 emails, and about 10% of them were bounced and Mailgun has suspended our account to investigate whether we are really using emails with users' approval. I just showed them the registration form and our meetup info where we collect the emails, then they enabled our account.

**Comment by distalx** [comment]
A few advantages for using MailChimp:
- It gives a  customization option for mailing list fields.
- We can schedule email deliveries according to recipient's timezone.
- Analytics are also good.
- 12000 monthly free emails 

The only downside is the number of subscribers: 2000
We have ~1500 subscribers already, but we don't have any stats at this point to know approximately how many monthly users we're starting off with.

So if we cross the limit of 2000 we can do two things:

1) Split mailing list by active readers (those who are clicking on our emails) and non-active users (those who instead of unsubscribing either keep deleting or marking our emails as a spam). We'll only send the second group important updates.
That's one way can manage our consumption under the 12,000 limit.

2) Switch to SendGrid.

**Comment by anbuselvan** [comment]
@lpatmo good to know about MailChimp and thanks for sharing the details. I like the alternate option #1, and the option #2 seems expensive than maintaining a droplet ($5 we can run our own mail server and send unlimited emails).

**Comment by lpatmo** [comment]
@distalx sent in a pull request that sends an invitation for any newly registered Slack signups to a Mailchimp invite. If they agree, their email gets adds to the list. /giphy YAY

Will keep this thread open for further discussion in case we migrate to another email provider in the future.

**Comment by wuworkshop** [comment]
@distalx @lpatmo - I just logged in to the app for the first time and got the Mailchimp "codebuddies: Please Confirm Subscription" email. Should we be calling the list "codebuddies list x"? Can the email be customized to explain what they are subscribing to?

**Comment by distalx** [comment]
@wuworkshop Sorry for the delayed response. 
we are adding users to the mailchimp list when they loggins in for the very first time. mailchimp sends a confirmation email behalf of us ! if user approves that, mailchimp will add that user to the mailing list. 

`codebuddies list x` list was just created for trial purpose - I guess we forget to replace that with our custom template !

**Comment by lpatmo** [comment]
A note: we can also use Slack API events to send email signups on Slack directly to Mailchimp (or Sparkpost) for newsletter sends.

**Comment by billglover** [comment]
Closing this issue as stale. If this feature is still of interest, please open a new issue and include a reference to this issue by including issue number #143 in the description.
