### ISSUE TITLE
digital badging

### ISSUE THREAD

**Issue by LaurenDoughty** [codebuddies/codebuddies#378]
This is a feature request. I'm interested in adding digital badging and levels/gamification.

**Comment by lpatmo** [comment]
I can imagine a "Hangout Leader" badge on the profile page for someone who's created at least three hangouts. And maybe a similar one for someone who's participated in at least five hangouts.

**Comment by adachiu** [comment]
We had started some discussion about gamification here #61 😄

**Comment by lpatmo** [comment]
Let's revisit this issue of badges after implementing some sort of points counter for users and groups (see: #829)

**Comment by lpatmo** [comment]
Re: badges -- maybe after a certain # of points, users will be entitled to a free CodeBuddies sticker? A free CodeBuddies t-shirt? Something they can get reimbursed from opencollective.com/codebuddies, assuming we have enough money there?

This'll be more in the future, since first I want to make sure contributors (folks who've been working on the site and been active helping out on Slack) get the first of the swag.

**Comment by billglover** [comment]
I'm closing this issue as stale. We can re-visit once work on #829 has made progress.
