### ISSUE TITLE
Design/UI feedback: can we improve the display of events?

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#696]
Complaints I've heard:
- The date is too small to read
- It's not clear that each event is tied to a study group (or the default `CB`, if no study group is tied to the event)
- Users want to be able to read more of the description, and not be forced to click through on the card to the event page itself

Current design:
See: http://codebuddies.org/hangouts

Here is a screenshot of an individual event card, before a user hovers over it:
![screen shot 2017-10-26 at 11 51 10 pm](https://user-images.githubusercontent.com/4512699/32091452-104e5950-baa9-11e7-9ee0-9eb2fc331a71.jpg)

Here is what a user will see after he or she hovers over the card:
![screen shot 2017-10-26 at 11 51 28 pm](https://user-images.githubusercontent.com/4512699/32091461-1fd8a16e-baa9-11e7-8968-b5294e7fd212.jpg)

Here is what a user will see after they've RSVPed to the event, if they hover over the card:
![screen shot 2017-10-26 at 11 51 42 pm](https://user-images.githubusercontent.com/4512699/32091474-2dfd04e2-baa9-11e7-89fa-04e795e7a5a3.jpg)

Some possible design alternatives:
1) Make each card bigger (two per row?)
2) Give each card its own row, like in an earlier design of the site:

![screen shot 2017-10-26 at 11 57 13 pm](https://user-images.githubusercontent.com/4512699/32091530-780c65f0-baa9-11e7-9dcf-70b6d6f75002.jpg)
(Credit: @adachiu)

**Comment by sahiljain95** [comment]
Hey @lpatmo . I was looking through this. I think that having two rows is sufficient. It will give enough information to get someone interested. Can change the truncated descrption length ~100 for this.

Also for the study group binding issue, I think adding the Study Group: CB/ Study Group: PyStudy will make it quite clear. The additional text will increase the tag width which will be in proportion to the increased card width. Let me know if these changes are fine. I'll create a PR then.

**Comment by angelocordon** [comment]
👍 on the alternative design

**Comment by mindovermiles262** [comment]
If events are based on dates, wouldn't it make sense to use a calendar display of some sort? Use colored events to differentiate programming languages

**Comment by lpatmo** [comment]
@mindovermiles262 Yes, that makes sense. :) Maybe something like what we'd see on meetup.com?

IMO redesigning the event cards area is especially needed because @railsstudent's recent PR fixed the display so that we can distinguish between past and upcoming/current events, and now it's more obvious that there needs to be some grid layout cleanup:

![screen shot 2017-10-27 at 10 04 25 pm](https://user-images.githubusercontent.com/4512699/32131452-ff4e56fe-bb62-11e7-9e53-2921bf6a46ff.jpg)

**Comment by angelocordon** [comment]
@lpatmo - I started thinking about this page recently and thought of a few things we can do to rework it better. I do have a few questions though: 

How does Hangouts relate to Study Groups? Is it important to showcase the old events?  I'm looking at this from a sense where I want to click on hangouts to see what's upcoming, not necessarily what I missed.

**Comment by angelocordon** [comment]
From an event card perspective, what do we consider important information for the event?

**Comment by lpatmo** [comment]
`How does Hangouts relate to Study Groups? Is it important to showcase the old events? I'm looking at this from a sense where I want to click on hangouts to see what's upcoming, not necessarily what I missed.` 

Heh... maybe not so important to showcase old events. I suppose we can think of hangouts as `virtual events`, and study groups as `meetup groups`.

> From an event card perspective, what do we consider important information for the event?

Great question. Will try to draw up some designs and paste the screenshots here this weekend. To start, maybe: 
- date
- start time
- end time
- topic (Study Group umbrella)
- title
- description about what's going to happen during the hangout
- silent/collaborative/teaching hangout indicator
- host
- # of participants RSVPed so far
- whether or not the event is happening RIGHT NOW

**Comment by angelocordon** [comment]
As per #547 

![image](https://user-images.githubusercontent.com/3891869/32988851-90713600-ccc1-11e7-82b4-6c084bf1a139.png)

We've cleaned up the cards a little bit to only show what's the most important information in terms of looking for hangouts.

The anatomy of a hangout card is as follows:

![image](https://user-images.githubusercontent.com/3891869/32988900-84cfa150-ccc2-11e7-89ea-6dee4c51e717.png)
+ The header / top row of the card contains the study group, the type of hangout (when the hangout is live or scheduled) and secondary options (contains `Report` and `Duplicate`).
+ Hangout Name
+ Date and Time of Hangout
+ Lastly, Hangout owner and number of members that subscribed to the hangout

During various states of the hangout: 
![image](https://user-images.githubusercontent.com/3891869/32988902-a000ad48-ccc2-11e7-8c6b-9e19edb7d5fa.png)
When the hangout is live, we don't need the date anymore and can be replaced with a `Live Now` tag. We can still showcase when it started as that can be helpful information to the user. When the event is within a day, we can remove the date and replace with `Today at` + time of event.  I think these combination of more "human" text can make reading cards easier or more natural.

When a user hovers over a card:
 
![image](https://user-images.githubusercontent.com/3891869/32988913-f6d91f56-ccc2-11e7-9ffd-668149576f0b.png)
+ The hangout owner and members gets replaced with a quick RSVP action button. 
+ Also note that the Hangout name is clickable to go to the hangout event page. (The description is no longer in the card but can still be accessible to the event page itself.)

If the user is subscribed to the card:

![image](https://user-images.githubusercontent.com/3891869/32988924-43e3567c-ccc3-11e7-9d00-60fb8c565acc.png)

+ A check mark appears on the top row
+ On hover, also allow to quickly un-rsvp

Past Events:

![image](https://user-images.githubusercontent.com/3891869/32988927-620de95a-ccc3-11e7-8cf2-47a38eb7d392.png)

One of the interesting ideas from the #codebuddies-meta convo was the concept of notes from a hangout, which gives the past hangouts some more value for showcasing them. A notebook icon can be used to signify that this particular hangout has notes that is open to public. 

Similarly with active events, we can lessen the text by calculating the time that has passed in order to display a more semantic format of when it happened.

Again, open for feedback!

**Comment by osanseviero** [comment]
Really cool! I like the new, fresh design.
Something that I'm wondering. Looking at it, I would suppose that I can click at the owner username (bethanyg in this case). As I understood it, when hovering over the card, that part would be replaced with the RSVP. Is that right?

**Comment by angelocordon** [comment]
Great catch @osanseviero! yeah that would totally not work

**Comment by angelocordon** [comment]
Maybe better off to swap the dates instead with the rsvp button? 

![image](https://user-images.githubusercontent.com/3891869/32989000-c17ee744-ccc4-11e7-91d2-93f2da8a1235.png)

**Comment by osanseviero** [comment]
Hah. I was going to say exactly that.

**Comment by osanseviero** [comment]
Mmm actually wondering...

With that design, would users be able to see when the hangouts will be? (after they do the RSVP).

**Comment by angelocordon** [comment]
and last correction, these cards shouldn't have a border (didn't see it with the bright blue background 😅 )

![image](https://user-images.githubusercontent.com/3891869/32989023-15d27f68-ccc5-11e7-969f-30cc4a262388.png)

**Comment by angelocordon** [comment]
> With that design, would users be able to see when the hangouts will be? (after they do the RSVP).

**Comment by osanseviero** [comment]
Perfect :)

**Comment by osanseviero** [comment]
Last question - sorry for multiple posts.

Is there any visual feedback to know which hangouts have been RSVP without hovering over them?

**Comment by angelocordon** [comment]
> Is there any visual feedback to know which hangouts have been RSVP without hovering over them?
Yup! The checkmarks on the top right should appear (not just on hover)

**Comment by osanseviero** [comment]
Cool! Didn't catch that detail.

**Comment by angelocordon** [comment]
My last concern I think is how long study group names and hangout names get :\ 

![image](https://user-images.githubusercontent.com/3891869/32989124-bda8b054-ccc5-11e7-8b38-d1f876afcefe.png)

We'll have to truncate them after a certain point - not sure if that's a _huge_ deal

**Comment by osanseviero** [comment]
Yes, that's an issue. For now I think that it could be ok to just leave it like that. Maybe we could do some resizing to allow the full name to fit in the card. The other would be to limit the length (I think there's already a limit) in the names. 

@lpatmo might be able to confirm.

**Comment by railsstudent** [comment]
@angelocordon  Text length could pose an issue in hangout since scrollbars appear when goal/ description is long and the scrollbar width takes up space and hide the text

**Comment by angelocordon** [comment]
@railsstudent I do agree that text length _is_ an issue and the scrollbars is a side effect of the problem :( My question is, should we enforce a ~50 character limit on hangout names or just truncate them? 

Or are hangout names incredibly important that we should just lengthen the hangout cards so that names can fit? We may be able to get way with 3 lines of text on the hang outs (so about ~75 chars).

**Comment by angelocordon** [comment]
@BethanyG @lpatmo - I'm going to answer your [comments](https://github.com/codebuddiesdotorg/codebuddies/issues/547#issuecomment-345514303) regarding the hangout card here to keep the threads succint 

> One thing I wonder if we can add to the design: when a user hovers over a hangout card, show the description. That way they wouldn't have to click through to see the goals and description (i.e. what to expect) before they decide to join.

I'm a bit weary of adding more hover complexities on the card - but a modal might be better here?

**Comment by angelocordon** [comment]
and a relevant point, should we also limit characters on study group names as well?

**Comment by osanseviero** [comment]
I think that a limit would be a good idea. I also agree with you that we shouldn't overload the card..

**Comment by lpatmo** [comment]
@angelocordon I can't believe we dropped this. I just re-discovered this thread and love your design for the card. Would it be all right with you if I created a CSS issue for this card design for Hacktoberfest?

**Comment by billglover** [comment]
With the re-design under #998 now complete, I'm closing this issue.
