### ISSUE TITLE
Today I Learn and What am I working on broken in hangout page

### ISSUE THREAD

**Issue by railsstudent** [codebuddies/codebuddies#761]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
No tweet is sent when Today I Learnt is submitted and What am I working on is not displayed

What is the expected behavior?
Tweet is sent when Today I Learnt is submitted and What am I working should show my status

Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)
all browsers

**Comment by stain88** [comment]
It's not just the tweeting that's an issue, number of people online doesn't seem to be being read properly, and toggling between the two tabs throws an error in console.

Confusingly, the before and after photos of release 0.9.91 both show 0 people learning, although since @lpatmo is signed in, I would have thought that would show at least 1. Maybe something from release 0.9.90?

**Comment by lpatmo** [comment]
I was not awake 8 hours ago; not sure how this issue was automatically triggered open once again...
