### ISSUE TITLE
The `stylus` package has been deprecated.

### ISSUE THREAD

**Issue by ApCoder123** [codebuddies/codebuddies#867]
Do you want to request a feature or report a bug?
Report a bug
What is the current behavior?
In Chrome devtools, you get a "The `stylus` package has been deprecated." error message. Specifically
 ```
The 'stylus' package has been deprecated.

To continue using the last supported version
of this package, pin your package version to
2.513.14 ('meteor add stylus@=2.513.14').
```
What is the expected behavior?
The newer version of the package should be used
Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)
Google Chrome, Windows 10. User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36`

**Comment by distalx** [comment]
@ApCoder123 Thanks a lot for filing this issue! Would you like to write a patch for this? We'd be more than happy to walk you through the steps involved.

**Comment by distalx** [comment]
This are my findings :

The official stylus packages has been deprecated. here is the fork of it  https://github.com/coagmano/meteor-stylus I try to replace `stylus` with `meteor-stylus` but getting the same warning `The 'stylus' package has been deprecated.`. 

`stylus` package is dependency for `accounts-ui-bootstrap-3`. in order to remove `stylus` we have to stop using  `accounts-ui-bootstrap-3`.
