### ISSUE TITLE
Users following 'blank screen' instructions for the 24x7 hangout end up in the wrong room

### ISSUE THREAD

**Issue by billglover** [codebuddies/codebuddies#930]
Do you want to request a feature or report a bug? **Bug**

What is the current behavior? 

> The 24x7 silent productivity hangout opens the `cbcoworking` hangout. If you launch the hangout by using the link provided in the guidance for what to do if you see a blank screen, you end up joining the `cb` hangout instead.

What is the expected behavior?

> When joining the 24x7 global silent productivity hangout I would expect the hangout loaded inline to be the same hangout as the one opened when clicking the alternate link provided in the guidance for what to do if you see a blank screen.

Which browser / OS are affected by this issue? Version 67.0.3396.99 (Official Build) (64-bit) on macOS High Sierra Version 10.13.6.

I expect this is not a browser specific bug but haven't tested this extensively. A brief look at the code indicates there may be an issue in the way links are constructed.

The coworking template includes the hangout frame and sets `hroom='coworking'`.

https://github.com/codebuddies/codebuddies/blob/371ed45a2d7118a328abf0bf3072fac0a6fc2df1/client/templates/other/coworking.html#L28-L32

The hangout frame constructs the name of the room from either the `_id` or the `hroom` name.

https://github.com/codebuddies/codebuddies/blob/371ed45a2d7118a328abf0bf3072fac0a6fc2df1/client/templates/hangout/hangout-frame.js#L3-L5

This is slightly different to the way the hangout name is constructed slightly later in the same file.

https://github.com/codebuddies/codebuddies/blob/371ed45a2d7118a328abf0bf3072fac0a6fc2df1/client/templates/hangout/hangout-frame.js#L111-L112

This is in contrast to the way the hangout URL is constructed for the instruction text.

https://github.com/codebuddies/codebuddies/blob/371ed45a2d7118a328abf0bf3072fac0a6fc2df1/client/templates/hangout/hangout-frame.html#L10-L12

The `_id` value doesn't appear to be set anywhere hence the link references a hangout called `cb`.

**Comment by praveeno** [comment]
i love to help

**Comment by railsstudent** [comment]
@praveeno   It is yours.

**Comment by lpatmo** [comment]
I really appreciate @billglover finding this bug, because honestly I thought the silent hangout room was meet.jit.si/cb for the longest time! :P (And didn't even realize that meet.jit.si/cbcoworking was loading.)

@praveeno I took a look, and I think this is what you need to do: 
1. Create a new helper function inside hangout-frame.js that returns `Template.instance().room.get()`, which according to line 4 on hangout-frame.js (` `cb${instance.data._id || instance.data.hroom}``) will return either the _id of the hangout page OR the hroom='coworking' passed in, which is what is happening here for the global silent hangout page.
2. Use that new helper variable in hangout-frame.html, so that the meet.jit.si URL contains _either_ the _id or the hroom='coworking'.  

Anyway, below is the git diff which hopefully makes it clearer:

diff --git a/client/templates/hangout/hangout-frame.html b/client/templates/hangout/hangout-frame.html
index b0cbf2d..b3ff048 100644
--- a/client/templates/hangout/hangout-frame.html
+++ b/client/templates/hangout/hangout-frame.html
@@ -8,7 +8,7 @@
 </div>
 
 <div class="alert alert-info margin-top-1 margin-bottom-1">
-  <p class="align-center">If you're seeing a blank screen, <a href="https://meet.jit.si/cb{{_id}}#config.startWithVideoMuted=true" target="_blank" id="joinHere">join here.</a> (New to Jitsi? Check out <a href="/images/codebuddies_jitsi_diagram.jpg" target="_blank">this diagram</a>.)</p>
+  <p class="align-center">If you're seeing a blank screen, <a href="https://meet.jit.si/{{room}}#config.startWithVideoMuted=true" target="_blank" id="joinHere">join here.</a> (New to Jitsi? Check out <a href="/images/codebuddies_jitsi_diagram.jpg" target="_blank">this diagram</a>.)</p>
 </div>
   <div id="hangout-container"></div>
   {{#if numParticipants}}
diff --git a/client/templates/hangout/hangout-frame.js b/client/templates/hangout/hangout-frame.js
index 4b97c32..b3ae676 100644
--- a/client/templates/hangout/hangout-frame.js
+++ b/client/templates/hangout/hangout-frame.js
@@ -126,6 +126,10 @@ Template.hangoutFrame.helpers({
       return appState.participants.length;
     }
     return 0;
+  },
+  room: function() {
+      return Template.instance().room.get();
   }
 });

@praveeno Let me know if you have any questions, or if you notice anything off when you run the app. If it looks okay, feel free to submit this in a PR.

**Comment by lpatmo** [comment]
@praveeno Does my comment make sense? Let me know!

**Comment by praveeno** [comment]
hey @lpatmo i caught somewhere, not able to help, any one who interested can pick this up

**Comment by lpatmo** [comment]
@praveeno No worries, thanks for letting me know! I might just commit this and submit it as a PR 😅

**Comment by peoray** [comment]
This is a meteor thing, right?

**Comment by lpatmo** [comment]
@peoray More of a wrong-link-buildup thing, but understanding a little of meteor helps; for example, in Meteor/Blaze (which is what we're using), there is the idea of a "helper function" which allows you to pass context variables into the template (ie the HTML). meteortips.com is a good resource site to get up to speed for Blaze, but we _will_ be moving to VueJS soon. :)

**Comment by peoray** [comment]
Can't wait for Vue!!!

**Comment by railsstudent** [comment]
@lpatmo  Is this issue fixed? Can it be closed? Thanks.
