### ISSUE TITLE
BUG: Study Groups page doesn't list all groups

### ISSUE THREAD

**Issue by wuworkshop** [codebuddies/codebuddies#938]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
On the Study Groups page (https://codebuddies.org/study-groups), when you scroll all the way down to the bottom of the page it doesn't load the full list of study groups. For example, I don't see the new "Colt Steele's JavaScript Algorithms and Data Structures Masterclass" study group. Searching for it does work though.

What is the expected behavior?
You should be able to see the full list of study groups or if there are a lot of study groups, then perhaps some sort of pagination.

Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)
I see this in Firefox Quantum 61.0.2 and Chrome 68.0.3440.106 on OS X El Capitan.

**Comment by lpatmo** [comment]
Note to new contributors: please check out docs.codebuddies.org for the docs on how to get started!

**Comment by AnnaDodson** [comment]
Hi, I would like to look at this one. Thanks

**Comment by lpatmo** [comment]
@AnnaDodson Thanks Anna. Let us know here or in the #cb-code channel on the CodeBuddies Slack if you get stuck! 

(In case you haven't seen it already, docs.codebuddies.org will hopefully be helpful.)

**Comment by AnnaDodson** [comment]
Hi, I think the problem seems to be the window scroll listener triggering the scroll handler multiple times before the study groups have loaded in. The scroll handler checks if the number to display limit is equal to the number of study groups currently loaded and increases the page limit if it's not. So by the second time it's hit, the page limit is greater because the study groups haven't had time to load in yet.

I can fix by stopping the scroll handler until the study groups get request has returned. So either a simple `isLoading` bool to set and check the page status before checking to load more in or if meteor/blaze has an inbuilt status of the page that can be checked?

But, also, the hangouts page has a button to load more rather than lazy loading them in - should the study groups page be the same?

I've posted in the #cb-code channel too :smiley:

**Comment by lpatmo** [comment]
Thanks for taking a look, @AnnaDodson! I'm leaning towards making the study groups work the same way as the hangouts page -- with a button to load more rather than lazy loading them in. @distalx -- do you have any thoughts on this?
